-- DROP TABLE APPLICATIONS;
-- DROP TABLE JOBS;
-- DROP TABLE JOBSEEKERS;
-- DROP TABLE EMPLOYERS;
-- DROP TABLE INDUSTRIES;
-- DROP TABLE USERS;

CREATE TABLE USERS(
    USER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    USER_EMAIL VARCHAR(50) UNIQUE,
    USER_PASSWORD VARCHAR(50),
    USER_TYPE INT
);

CREATE TABLE INDUSTRIES(
    IND_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    IND_NAME VARCHAR(100)
);

INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('user1@gmail.com', 'user1', 1);
INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('user2@gmail.com', 'user2', 1);
INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('user3@gmail.com', 'user3', 1);

INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('employer1@gmail.com', 'employer1', 2);
INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('employer2@gmail.com', 'employer2', 2);
INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('employer3@gmail.com', 'employer3', 2);

INSERT INTO INDUSTRIES (IND_NAME) VALUES ('INFORMATION TECHNOLOGY');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('HEALTHCARE');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('SALES');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('EDUCATION');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('FINANCE');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('MARKETING');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('ENGINEERING');
INSERT INTO INDUSTRIES (IND_NAME) VALUES ('HOSPITALITY');

CREATE TABLE EMPLOYERS(
    EMP_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    USER_ID INTEGER references USERS(USER_ID) ON DELETE CASCADE,
    EMP_NAME VARCHAR(50),
    EMP_ADDRESS VARCHAR(50),
    EMP_NUMBER VARCHAR(50)
);

INSERT INTO EMPLOYERS (USER_ID, EMP_NAME, EMP_ADDRESS, EMP_NUMBER)
    VALUES (4, 'EMPLOYER 1', 'MANILA', '12345678912');
INSERT INTO EMPLOYERS (USER_ID, EMP_NAME, EMP_ADDRESS, EMP_NUMBER)
    VALUES (5, 'EMPLOYER 2', 'MANILA', '12345678912');
INSERT INTO EMPLOYERS (USER_ID, EMP_NAME, EMP_ADDRESS, EMP_NUMBER)
    VALUES (6, 'EMPLOYER 3', 'MANILA', '12345678912');

CREATE TABLE JOBSEEKERS(
    SEEKER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    USER_ID INTEGER references USERS(USER_ID) ON DELETE CASCADE,
    SEEKER_FNAME VARCHAR(50),
    SEEKER_LNAME VARCHAR(50),
    SEEKER_ADDRESS VARCHAR(50),
    SEEKER_NUMBER VARCHAR(50)
);

CREATE TABLE JOBS(
    JOB_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    EMP_ID INTEGER references EMPLOYERS(EMP_ID),
    JOB_TITLE VARCHAR(50),
    JOB_LOCATION VARCHAR(100),
    JOB_LEVEL INT,
    JOB_DESC VARCHAR(500),
    JOB_RESP VARCHAR(500),
    JOB_REQS VARCHAR(500),
    JOB_BENEFIT VARCHAR(500),
    INDUSTRY_ID INTEGER references INDUSTRIES(IND_ID),
    JOB_SALARY_MIN VARCHAR(50),    
    JOB_SALARY_MAX VARCHAR(50),
    JOB_TYPE INT,
    JOB_ISACTIVE INT DEFAULT 0
);

CREATE TABLE APPLICATIONS(
    APP_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    SEEKER_ID INTEGER REFERENCES JOBSEEKERS(SEEKER_ID),
    JOB_ID INTEGER REFERENCES JOBS(JOB_ID),
    APP_STATUS INT DEFAULT 0,
    APP_REMARKS VARCHAR(500)
);

INSERT INTO JOBS (EMP_ID, JOB_TITLE, JOB_LOCATION, JOB_LEVEL,
        JOB_DESC, JOB_RESP, JOB_REQS, JOB_BENEFIT, INDUSTRY_ID,
        JOB_SALARY_MIN, JOB_SALARY_MAX, JOB_TYPE) VALUES 
        (1,'TITE', 'TITE', 2, 'TITE', 'TITE', 'TITE','TITE',2, '1000', '2000',2);

--APP STATUSES
--0 = PENDING
--1 = ACCEPTED
--3 = REJECTED

--JOB TYPES
--0 = FRESH GRAD
--1 = CONTRACTUAL
--2 = INTERNSHIP
--3 = PART-TIME
--4 = FULL TIME

--JOB INDUSTRIES
--1 = INFORMATION TECHNOLOGY
--2 = HEALTHCARE
--1 = SALES
--2 = EDUCATION
--1 = FINANCE
--2 = MARKETING
--1 = ENGINEERING
--2 = HOSPITALITY

--JOB ISOPEN
--0 = TRUE
--1 = FALSE

-- INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('user3@gmail.com', 'user3', 1);
-- 
-- INSERT INTO USERS (USER_EMAIL, USER_PASSWORD, USER_TYPE) VALUES ('user4@gmail.com', 'user4', 1);
-- 
-- INSERT INTO JOBSEEKERS (USER_ID, SEEKER_FNAME, SEEKER_LNAME, SEEKER_ADDRESS, SEEKER_NUMBER) VALUES (4, 'JAY', 'AMBAL', 'PROJECT 6', 123);


